spring.datasource.url=jdbc:mysql://localhost:3306/pdv?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=pdv
spring.datasource.password=password2025

server.port=8080

spring.flyway.enabled=false
spring.data.web.pageable.max-page-size=20

spring.jpa.hibernate.ddl-auto=none

logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

#spring.jmx.enabled=false
